group: fe
name: easi-jssdk
build: yarn install --pure-lockfile && yarn easi-assets-deploy --env ${profile} --version ${version} --versionBuild ${version_build}
artifacts:
  - destination: append-to-notification
    artifact: ./devops-notification
notifications:
  feishu:
    webhook: []
