group: fe
name: easi-jssdk
build: yarn install --pure-lockfile && yarn easi-assets-deploy --env ${profile} --version ${version} --versionBuild ${version_build}
artifacts:
  - destination: append-to-notification
    artifact: ./devops-notification
notifications:
  feishu:
    webhook:
      - https://open.feishu.cn/open-apis/bot/v2/hook/7232fb5a-8ef2-4b77-8045-ce009bc8b637
