import { getEnv } from '../utils/env';
import {
  config,
  ready,
  error,
  getNetworkType,
  checkJsApi,
  updateWechatTimelineShareData,
  updateWechatMessageShareData,
  updateFacebookTimelineShareData,
  copy,
  chooseImage,
  getLocalImageData,
  previewImage,
  openLocation,
  getLocation,
  scanQRCode,
  scanBarcode,
  closeWindow,
  hideMenuBar,
  showMenuBar,
  hideMenuItems,
  showMenuItems,
  hideNavBar,
  showNavBar,
  openWebPage,
  openAppPage,
  getUserInfo,
} from '../base';

const easi = {
  config,
  ready,
  error,
  getEnv,
  getNetworkType,
  checkJsApi,
  updateWechatTimelineShareData,
  updateWechatMessageShareData,
  updateFacebookTimelineShareData,
  copy,
  chooseImage,
  getLocalImageData,
  previewImage,
  openLocation,
  getLocation,
  scanQRCode,
  scanBarcode,
  closeWindow,
  hideMenuBar,
  showMenuBar,
  hideMenuItems,
  showMenuItems,
  hideNavBar,
  showNavBar,
  openWebPage,
  openAppPage,
  getUserInfo,
};

export default easi;
